name: CI Model Retraining Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/'

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- HAPUS STEP "Set up Python" ---
    # SAYA SUDAH MENGHAPUS STEP 'setup-python' AGAR TIDAK BENTROK
    # Kita langsung gunakan Conda saja.

    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: diabetes_ml_env
        environment-file: MLProject/conda.yaml
        python-version: 3.10
        auto-activate-base: false

    - name: Run MLflow Project Training
      # Shell bash -l {0} wajib agar environment conda terdeteksi
      shell: bash -l {0}   
      run: |
        # Fix untuk masalah "Run ID not found" (error sebelumnya)
        export MLFLOW_TRACKING_URI=file://$(pwd)/mlruns
        
        # Jalankan training
        mlflow run MLProject/ 

    - name: Upload MLflow Tracking Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-tracking-data
        path: mlruns/
        retention-days: 5

    - name: Success Message
      run: echo "Model training and artifact upload complete!"
