name: CI Model Retraining Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/'

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- HAPUS STEP "Set up Python" ---
    # Kita langsung gunakan Conda saja agar tidak bentrok

    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: diabetes_ml_env
        environment-file: MLProject/conda.yaml
        python-version: 3.10
        auto-activate-base: false

    - name: Run MLflow Project Training
      shell: bash -l {0}   # Menggunakan shell login agar Conda aktif
      run: |
        # FIX PENTING: Set Absolute Path untuk Tracking URI
        # Ini mencegah error "Run ID not found" saat script berjalan
        export MLFLOW_TRACKING_URI=file://$(pwd)/mlruns
        
        # Jalankan MLflow
        mlflow run MLProject/ 

    - name: Upload MLflow Tracking Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-tracking-data
        path: mlruns/
        retention-days: 5

    - name: Success Message
      run: echo "Model training and artifact upload complete!"
