name: CI Model Retraining Workflow

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Kriteria 3: Menggunakan versi Python 3.10 secara eksplisit tanpa matrix strategy
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: diabetes_ml_env
          environment-file: MLProject/conda.yaml
          python-version: "3.10"
          auto-activate-base: false
          # Menggunakan mamba untuk penyelesaian dependensi yang lebih cepat dan stabil
          mamba-version: "*"
          use-mamba: true

      - name: Run MLflow Project Training
        shell: bash
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate diabetes_ml_env

          # Jalankan skrip secara langsung untuk menghindari konflik Run ID
          cd MLProject/
          python modelling.py

      # Kriteria 3: Menyimpan hasil training sebagai Artifact di GitHub Actions
      - name: Upload MLflow Tracking Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-tracking-data
          path: mlruns/  # Folder ini berisi bukti Kriteria 2 (Model Artifacts)
          retention-days: 5

      - name: Success Message
        run: echo "Model training and artifact upload complete!"
