name: CI Model Retraining Workflow

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [ '3.10' ] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- BARU: Ganti setup-miniconda dengan setup-python dan Pip install ---
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        # Menginstal semua paket menggunakan Pip dari file yang baru dibuat
        pip install -r MLProject/requirements.txt
        
    # --- Perubahan di Langkah Run MLflow Project ---
    # Kita tidak lagi perlu mengaktifkan Conda environment
    - name: Run MLflow Project Training
      run: |
        # Tambahkan flag --env-manager=local agar MLflow tidak mencari Conda
        mlflow run MLProject/ -P use_conda=False --env-manager=local

    - name: Upload MLflow Tracking Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-tracking-data
        path: mlruns/
        retention-days: 5
        
    - name: Success Message
      run: echo "Model training and artifact upload complete!"
