name: CI Model Retraining Workflow

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: diabetes_ml_env
          environment-file: MLProject/conda.yaml
          python-version: "3.10"
          auto-activate-base: false
          mamba-version: "*"
          use-mamba: true

      - name: Run MLflow Project Training
        # PENTING: Menggunakan shell login agar path conda & mlflow terdeteksi
        shell: bash -l {0}
        run: |
          # Instal mlflow di runner agar perintah 'mlflow' tersedia
          pip install mlflow

          # Jalankan sebagai MLflow Project sesuai Kriteria 3
          # Menggunakan --env-manager local karena environment sudah disiapkan oleh miniconda
          mlflow run MLProject/ --env-manager local

      - name: Upload MLflow Tracking Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-tracking-data
          path: mlruns/
          retention-days: 5

      - name: Success Message
        run: echo "Model training and artifact upload complete!"
