name: CI Model Retraining Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**' # Hanya jalankan jika ada perubahan pada folder MLProject

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda Environment
      # Menggunakan action setup-conda adalah cara termudah untuk lingkungan ML
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: diabetes_ml_env
        environment-file: MLProject/conda.yaml
        python-version: 3.10
        auto-activate-base: false

    - name: Install dependencies (optional, jika Conda gagal)
      # Langkah cadangan untuk menginstal dependensi
      shell: bash
      run: |
        conda activate diabetes_ml_env
        pip install -r MLProject/conda.yaml --ignore-installed

    - name: Run MLflow Project Training
      shell: bash
      run: |
        conda activate diabetes_ml_env
        # Menjalankan project MLflow yang akan menjalankan modelling.py
        mlflow run MLProject/ -P use_conda=False

    # Langkah Kriteria Skilled: Menyimpan Artefak MLflow Tracking
    - name: Upload MLflow Tracking Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-tracking-data
        # MLflow secara default membuat folder mlruns di root project (Workflow-CI)
        path: mlruns/
        retention-days: 5
        
    - name: Success Message
      run: echo "Model training and artifact upload complete!"
